AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vlilleAgent

  Sample SAM Template for vlilleAgent

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  GetVlilleInfoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_info/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
     

Outputs:
  GetVlilleInfoFunction:
    Description: "Get Vlille infos Lambda Function ARN"
    Value: !GetAtt GetVlilleInfoFunction.Arn
  GetVlilleInfoFunctionIamRole:
    Description: "Implicit IAM Role created for Get Vlille infos function"
    Value: !GetAtt GetVlilleInfoFunctionRole.Arn
